### ISSUE TITLE
'Bootstrap' prefix ... a lot of typing.

### ISSUE THREAD

**Issue by RdeWilde** [hhvm/xhp-bootstrap#34]
I think it would be a lot more comfortable if we could use a much shorter prefix like 'bs' (BootStrap) or 'tb' (Twitter Bootstrap). It would save typing and bytes and makes the code look cleaner imho.

Additionally, alias to parent prefix would be cool; https://github.com/facebook/xhp/issues/64

**Comment by fredemmott** [comment]
Closing as this is eventually going to get solved by https://github.com/facebook/xhp-lib/issues/64 and we don't want to support a temporary workaround.
